### ISSUE TITLE
I've translated it to Chinease， but something wrong

### ISSUE THREAD

**Issue by Cliencer** [Fexty12573/mhr-charm-item-editor#1]
![image](https://user-images.githubusercontent.com/79413453/150660641-a627005b-4031-4800-8eb2-6cd4f11de0e5.png)
[简体中文.zip](https://github.com/Fexty12573/mhr-charm-item-editor/files/7919565/default.zip)

**Comment by Fexty12573** [comment]
Should be fixed in 6d3f38cd8902911166c05b7a291b30a9e7ab5675.
