### ISSUE TITLE
Suggestion: Allow charms to be exported to skill name instead of skill number.

### ISSUE THREAD

**Issue by Patcheresu** [Fexty12573/mhr-charm-item-editor#2]
I'll be real with you, this is because I just spent 30 minutes making an Excel setup just to make this data importable into the Armor Set Search when the only change that really needed to be made was swapping out the content of the first and third column (skill names). I wish I knew C++ so I could have just made a pull request instead 😭 https://mhrise.wiki-db.com/sim/

**Comment by Fexty12573** [comment]
Have considered making that an option. Will maybe add in the future.
