### ISSUE TITLE
Latest version is now incompatible with MH:R v3.9

### ISSUE THREAD

**Issue by Daniel-Poke** [Fexty12573/mhr-charm-item-editor#6]
Lots of people commenting on the Nexus link but this is where the real business happens 😆

Are there any active contributors on this ready and willing to update this to be compatible with the latest version? If not the whole app, just the charm functionality?

I am unfortunately only a C# dev so fixing this would be quite the task.

**Comment by Fexty12573** [comment]
Fixed in [newest release](https://github.com/Fexty12573/mhr-charm-item-editor/releases/tag/2.3.0)
