### ISSUE TITLE
Editing HR and Hub progress

### ISSUE THREAD

**Issue by manelis** [Fexty12573/mhr-charm-item-editor#9]
Hello, how viable would it be to have this support editing the HR and the hub progress? I assume its only a mater of finding the offsets and setting the values? I would like to try to somewhat recreate my switch state and seems there is no tool available to achieve it?

I read you have no intention to offer support of new features, but I maybe would do it if it seems easily achievable.

**Comment by Fexty12573** [comment]
Modifying HR is not an issue that should be pretty straight forward. However editing Hub progress is a different matter. The issue with that is that you have to modify flags inside the savedata, which can go wrong very quickly.

I am currently working on a rewrite of the editor and I might add some new features so I will consider it.
